name: Backmerge main → develop

on:
  push:
    branches:
      - main
    paths:
      - .openzeppelin/**

jobs:
  backmerge:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create back-merge PR
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          branch: bot/backmerge-main-to-develop
          base: develop
          title: "chore: back-merge main → develop"
          body: "Automatic back-merge after push to main for manifest updates"
          commit-message: "chore: back-merge main → develop [skip ci]"
          labels: automated
          delete-branch: true

      - name: Enable auto-merge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        run: |
          gh pr merge --auto --merge "${{ steps.cpr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
