name: PR Tests

on:
  pull_request:
    branches:
      - develop
      - main

permissions:
  contents: read

env:
  HARDHAT_DISABLE_TELEMETRY: "1"

jobs:
  tests:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
